GET http://localhost:5000/api/product HTTP/1.1

POST  http://localhost:5000/api/products/ HTTP/1.1

GET http://localhost:5000/api/products/61a76ec4cc478291dd4999b1 HTTP/1.1


content-type: application/json

