

GET http://localhost:5000/api/product HTTP/1.1
###
POST  http://localhost:5000/api/products/ HTTP/1.1
###
GET http://localhost:5000/api/products/61a76ec4cc478291dd4999b1 HTTP/1.1


content-type: application/json
###

POST http://localhost:5000/api/user/login
content-type: application/json

{
    "email":"nguyendainam19711@gmail.com",
    "password": "nguyendainam"
}


###
POST http://localhost:5000/api/user/register
content-type: application/json

{
    "email":"nguyendainam19711@gmail.com",
    "password": "nguyendainam",
    "name" : "Nam"
 
}


###
POST http://localhost:5000/api/user/profile
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWU3OTNlNTE5ZDdlMTRjZmI1YjI3YmEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQyNTY2OTQ3LCJleHAiOjE2NDI1Njc1NDd9.22lVPpTV0P4bbdcKCTTRlkxXp0ppgdGL4RF6n30f6F2

